# Generated by Django 5.1 on 2024-11-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0003_chatmodel_profile_online_status_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
