# Generated by Django 5.1 on 2024-11-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hadith', '0004_alter_appuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
